name: No permission control

on: push

permissions:
    contents: read
jobs:

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Try to push
              run: |
                git config --global user.name "test"
                git config --global user.email "test@test.com"
                git commit --allow-empty -m "test commit"
                git push
           