name: No permission control

on: push

permissions: {}
jobs:

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: push change 
              run: |
                echo "update" >> file.txt
                git config --global user.name "bot"
                git config --global user.email "bot@bot.com"
                git add .
                git commit -m "auto update"
                git push
           